# Header

menu:
  用户中心: http://demo.ucenter.szjlxh.com
  开放平台: http://iat.net.cn/ucenter-open/

# SubNav
subnav:
  github: "https://github.com/yaoshanliang"
  # weibo: "#"
  # rss: "#"
  # zhihu: "#"
  # douban: "#"
  mail: "mailto:i@iat.net.cn"
  # facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: more
fancybox: true
# mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
# google_analytics:
baidu_analytics: 'a8f517fee81bd1ee9a017d6f0cbfe789'
# favicon: /avatar.jpg

#你的头像url
avatar: /avatar.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: iatboy

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: 'Archive'
  tagcloud: 'Tags'
  friends: 'Links'
  aboutme: 'About'

friends:
  green: http://limaolong.cn/
  huanming: http://wanghuanming.com/
  kaiyao: http://sukai.me/
  may: http://maywanting.wang/
  mike: http://mikecoder.cn/
  zale: http://zalezone.cn/

aboutme: Just a beginner.<br /><a href='https://github.com/yaoshanliang/about' target='_blank'>profile</a>
